services:
  backend:
    image: ${DOCKER_REGISTRY-}api:latest
    build:
      context: .
      dockerfile: Web3D.API/Dockerfile
    depends_on:
      - postgres_db
    env_file:
      - Web3D.API/.env

  client:
    image: client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: ["npm", "run", "dev"]

  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=web3ddb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: